export type Role = 'Administrador' | 'Editor' | 'Lector';
export type ResourceKind = 'diagram' | 'note' | 'document' | 'image' | 'link' | 'score';
export interface Member { name: string; initials: string; color: string; role: Role; source?: string; }
export interface Group { id: string; name: string; description: string; color: string; symbol: string; members: Member[]; }
export interface Project { id: string; name: string; description: string; groupId: string | null; sharedGroupIds: string[]; color: string; icon: 'layers' | 'music' | 'pen' | 'spark'; status: 'En curso' | 'Planificación' | 'Completado'; pinned: boolean; members: Member[]; }
export interface Resource { id: string; projectId: string; title: string; kind: ResourceKind; folder: string; author: string; initials: string; color: string; date: string; version: number; size: string; content: string; url?: string; mime?: string; originalName?: string; starred?: boolean; comments: {author: string; text: string; date: string}[]; }
export interface Task { id: string; projectId: string; title: string; status: 'Pendiente' | 'En curso' | 'Completada'; assignee: string; due: string; }
export interface Thread { id: string; projectId: string; author: string; initials: string; color: string; title: string; body: string; date: string; replies: {author: string; body: string}[]; }
export interface Activity { id: string; projectId: string; author: string; initials: string; color: string; action: string; target: string; date: string; }
export const me: Member = {name:'Andrés Hidalgo', initials:'AH', color:'purple', role:'Administrador'};
const clara: Member = {name:'Clara Soto', initials:'CS', color:'pink', role:'Editor'};
const mateo: Member = {name:'Mateo Rojas', initials:'MR', color:'blue', role:'Editor'};
const vale: Member = {name:'Valentina Díaz', initials:'VD', color:'amber', role:'Editor'};
export const initialGroups: Group[] = [
 {id:'ucn',name:'Equipo UCN',description:'Diseñamos y construimos juntos. Proyectos, documentación y decisiones del equipo.',color:'purple',symbol:'U',members:[me,clara,mateo]},
 {id:'norte',name:'Banda Norte',description:'Un lugar para nuestras canciones, ensayos y próximos escenarios.',color:'coral',symbol:'N',members:[me,mateo,vale,clara]},
 {id:'prisma',name:'Estudio Prisma',description:'Identidades y experiencias digitales que se construyen en equipo.',color:'blue',symbol:'P',members:[me,clara,vale]},
];
export const initialProjects: Project[] = [
 {id:'plataforma',name:'Plataforma colaborativa',description:'Diseño y desarrollo de nuestro espacio de trabajo compartido.',groupId:'ucn',sharedGroupIds:[],color:'purple',icon:'layers',status:'En curso',pinned:true,members:[me,clara,mateo]},
 {id:'sesiones',name:'Sesiones de septiembre',description:'Partituras, ideas y preparativos para nuestro próximo concierto.',groupId:'norte',sharedGroupIds:[],color:'coral',icon:'music',status:'En curso',pinned:true,members:[me,mateo,vale,clara]},
 {id:'identidad',name:'Una nueva identidad',description:'Exploraciones y acuerdos para la próxima etapa del estudio.',groupId:'prisma',sharedGroupIds:[],color:'blue',icon:'pen',status:'Planificación',pinned:false,members:[me,clara,vale]},
 {id:'repertorio',name:'Repertorio 2026',description:'Nuestro catálogo de canciones, arreglos y versiones.',groupId:'norte',sharedGroupIds:[],color:'coral',icon:'music',status:'En curso',pinned:false,members:[me,mateo,vale,clara]},
 {id:'ideas',name:'Cuaderno de ideas',description:'Experimentos, referencias y pequeñas cosas que pueden crecer.',groupId:null,sharedGroupIds:['ucn'],color:'amber',icon:'spark',status:'Planificación',pinned:false,members:[me]},
 {id:'investigacion',name:'Investigación de usuarios',description:'Entrevistas y hallazgos que dan forma a la plataforma.',groupId:'ucn',sharedGroupIds:[],color:'blue',icon:'layers',status:'Completado',pinned:false,members:[me,clara,mateo]},
];
export const initialResources: Resource[] = [
 {id:'arquitectura',projectId:'plataforma',title:'Arquitectura técnica',kind:'diagram',folder:'Diseño técnico',author:'Andrés Hidalgo',initials:'AH',color:'purple',date:'Hace 20 min',version:3,size:'Diagrama',content:'La interfaz React con TypeScript se conecta mediante una API REST al backend monolítico. Los recursos conservan su identidad y se relacionan con cada proyecto.',starred:true,comments:[{author:'Clara Soto',text:'La separación entre recursos y proyectos quedó mucho más clara en esta versión.',date:'Hace 15 min'}]},
 {id:'brief',projectId:'plataforma',title:'Brief del proyecto',kind:'note',folder:'Documentación',author:'Clara Soto',initials:'CS',color:'pink',date:'Hace 1 h',version:2,size:'Nota',content:'Un espacio para trabajar mejor\n\nCentralizar archivos, conversaciones y decisiones de cada proyecto, sin perder el contexto.\n\nObjetivos\n• Encontrar la información vigente en pocos pasos.\n• Reutilizar los mismos grupos en distintos proyectos.\n• Hacer visibles los permisos de cada persona.\n\nPrimera entrega\nExplorador de recursos, página del grupo y experiencia de compartir.',starred:true,comments:[]},
 {id:'wireframes',projectId:'plataforma',title:'Mapa de pantallas',kind:'image',folder:'Diseño técnico',author:'Clara Soto',initials:'CS',color:'pink',date:'Hace 2 h',version:1,size:'Esquema',content:'Proyectos → Proyecto → Recursos. Grupos → Grupo → Proyectos. El detalle conserva la navegación de origen.',comments:[]},
 {id:'reunion',projectId:'plataforma',title:'Acuerdos · 16 septiembre',kind:'note',folder:'Reuniones',author:'Mateo Rojas',initials:'MR',color:'blue',date:'Hace 3 h',version:1,size:'Nota',content:'Reunión de diseño\n16 de septiembre de 2026\n\nParticipantes\nAndrés, Clara y Mateo\n\nAcuerdos\n1. Los recursos serán la vista principal del proyecto.\n2. Compartir un enlace no cambia los permisos.\n3. La primera versión tendrá roles de lector, editor y administrador.\n\nPróximos pasos\nValidar la navegación y revisar la experiencia en móvil.',comments:[]},
 {id:'permisos',projectId:'plataforma',title:'Matriz de permisos',kind:'document',folder:'Documentación',author:'Andrés Hidalgo',initials:'AH',color:'purple',date:'Ayer',version:2,size:'Documento',content:'Matriz de permisos\n\nLector\nPuede consultar los recursos.\n\nEditor\nPuede añadir archivos, notas, comentarios y tareas.\n\nAdministrador\nPuede gestionar accesos, integrantes y ajustes.\n\nPropietario\nConserva las acciones de transferencia y eliminación definitiva.',comments:[]},
 {id:'referencias',projectId:'plataforma',title:'Referencias de interacción',kind:'link',folder:'Diseño técnico',author:'Clara Soto',initials:'CS',color:'pink',date:'Ayer',version:1,size:'Enlace',content:'Patrones accesibles para diálogos, pestañas y navegación de la aplicación.',url:'https://www.w3.org/WAI/ARIA/apg/',comments:[]},
 {id:'partitura',projectId:'sesiones',title:'Viento del norte · guitarra',kind:'score',folder:'Partituras',author:'Mateo Rojas',initials:'MR',color:'blue',date:'Hace 35 min',version:2,size:'Guía de acordes',content:'Viento del norte\nGuitarra · arreglo de ensayo\n\nCompás: 4/4 · Tempo: 92 BPM\n\nINTRO\n| Am | F | C | G |\n\nVERSO\n| Am | F | C | G |\n| Am | F | C | G |\n\nESTRIBILLO\n| F | G | Am | Am |\n\nIndicaciones\nEntrar suave. Repetir el estribillo dos veces. Cierre conjunto después del último compás.',starred:true,comments:[]},
 {id:'ensayo',projectId:'sesiones',title:'Indicaciones para el ensayo',kind:'note',folder:'Ensayos',author:'Valentina Díaz',initials:'VD',color:'amber',date:'Hace 1 h',version:1,size:'Nota',content:'Ensayo del viernes\n\nEmpezamos con el repertorio acústico.\n\n1. Revisar la entrada de las segundas voces.\n2. Practicar la transición entre las dos primeras canciones.\n3. Grabar una toma completa al final.\n\nTraer las partituras actualizadas y un lápiz.',comments:[]},
 {id:'setlist',projectId:'sesiones',title:'Setlist del concierto',kind:'document',folder:'Partituras',author:'Andrés Hidalgo',initials:'AH',color:'purple',date:'Ayer',version:1,size:'Documento',content:'Sesiones de septiembre\n\n01 · Viento del norte\n02 · Ciudad costera\n03 · Después de la lluvia\n04 · Volver a casa\n05 · El último acorde\n\nDuración aproximada: 30 minutos.',comments:[]},
 {id:'catalogo',projectId:'repertorio',title:'Canciones y tonalidades',kind:'note',folder:'Repertorio',author:'Mateo Rojas',initials:'MR',color:'blue',date:'Ayer',version:1,size:'Nota',content:'Catálogo 2026\n\nViento del norte · La menor\nCiudad costera · Sol mayor\nDespués de la lluvia · Re mayor\nVolver a casa · Do mayor',comments:[]},
 {id:'marca',projectId:'identidad',title:'Dirección de marca',kind:'note',folder:'Exploraciones',author:'Clara Soto',initials:'CS',color:'pink',date:'Ayer',version:1,size:'Nota',content:'La próxima etapa de Prisma\n\nClaridad, cercanía y curiosidad.\n\nQueremos una identidad flexible, que mantenga su carácter tanto en una presentación como en una experiencia digital.',comments:[]},
 {id:'ideas-nota',projectId:'ideas',title:'Pequeños experimentos',kind:'note',folder:'Ideas',author:'Andrés Hidalgo',initials:'AH',color:'purple',date:'Ayer',version:1,size:'Nota',content:'Ideas por explorar\n\n• Una vista que conecte decisiones con sus documentos.\n• Una forma de reutilizar grupos sin repetir invitaciones.\n• Plantillas ligeras para proyectos personales.',comments:[]},
 {id:'hallazgos',projectId:'investigacion',title:'Hallazgos principales',kind:'document',folder:'Entrevistas',author:'Clara Soto',initials:'CS',color:'pink',date:'12 sep',version:1,size:'Documento',content:'Lo que aprendimos\n\nLas personas necesitan reconocer el documento vigente. Los equipos suelen repetirse. Compartir debe ser predecible.',comments:[]},
];
export const initialTasks: Task[] = [
 {id:'t1',projectId:'plataforma',title:'Definir la estructura de navegación',status:'Completada',assignee:'AH',due:'16 sep'},
 {id:'t2',projectId:'plataforma',title:'Revisar el flujo de compartir',status:'En curso',assignee:'CS',due:'18 sep'},
 {id:'t3',projectId:'plataforma',title:'Validar las vistas en móvil',status:'Pendiente',assignee:'MR',due:'21 sep'},
 {id:'t4',projectId:'plataforma',title:'Preparar la presentación del prototipo',status:'Pendiente',assignee:'AH',due:'23 sep'},
 {id:'t5',projectId:'sesiones',title:'Revisar las segundas voces',status:'En curso',assignee:'VD',due:'18 sep'},
 {id:'t6',projectId:'sesiones',title:'Confirmar el orden del setlist',status:'Pendiente',assignee:'MR',due:'20 sep'},
];
export const initialThreads: Thread[] = [{id:'th1',projectId:'plataforma',author:'Clara Soto',initials:'CS',color:'pink',title:'¿Cómo mostramos la versión vigente?',body:'Propongo que el recurso mantenga siempre el mismo enlace y que la versión aparezca junto al nombre. Así evitamos compartir archivos desactualizados.',date:'Hace 2 h',replies:[{author:'Andrés Hidalgo',body:'De acuerdo. Dejemos también el autor y la fecha visibles en el detalle.'}]},{id:'th2',projectId:'sesiones',author:'Mateo Rojas',initials:'MR',color:'blue',title:'Transición al segundo tema',body:'¿Probamos mantener el acorde final y entrar directamente con la guitarra?',date:'Hace 1 h',replies:[]}];
export const initialActivity: Activity[] = [
 {id:'a1',projectId:'plataforma',author:'Andrés',initials:'AH',color:'purple',action:'actualizó',target:'Arquitectura técnica',date:'Hace 20 min'},
 {id:'a2',projectId:'plataforma',author:'Clara',initials:'CS',color:'pink',action:'editó',target:'Brief del proyecto',date:'Hace 1 h'},
 {id:'a3',projectId:'plataforma',author:'Clara',initials:'CS',color:'pink',action:'añadió',target:'Mapa de pantallas',date:'Hace 2 h'},
 {id:'a4',projectId:'plataforma',author:'Mateo',initials:'MR',color:'blue',action:'creó una nota',target:'Acuerdos · 16 septiembre',date:'Hace 3 h'},
 {id:'a5',projectId:'sesiones',author:'Mateo',initials:'MR',color:'blue',action:'actualizó',target:'Viento del norte · guitarra',date:'Hace 35 min'},
];
