'use client';
import { useState, useEffect, useRef, type FormEvent } from 'react';
import { Upload, Plus, Link2, LockKeyhole, Copy, Users, X, FileText, Info } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { toast } from 'sonner';
import { useWorkspace } from './store';
import { Avatar, Choice } from './ui';
import { me, type Project, type Group, type Resource, type ResourceKind, type Role, type Member } from './data';
import type { CreateMode } from './workspace';

const labels:Record<CreateMode,{title:string;description:string;action:string}>={
 project:{title:'Un nuevo proyecto',description:'Dale un lugar a lo que quieres construir.',action:'Crear proyecto'},
 group:{title:'Crea tu grupo',description:'Reúne a las personas con las que trabajas una y otra vez.',action:'Crear grupo'},
 note:{title:'Una nueva nota',description:'Una idea, un acuerdo o algo que vale la pena recordar.',action:'Guardar nota'},
 file:{title:'Añadir archivos',description:'Diagramas, imágenes, partituras y documentos, en un mismo lugar.',action:'Añadir archivos'},
 link:{title:'Guardar un enlace',description:'Conserva una referencia junto al resto del proyecto.',action:'Guardar enlace'},
 task:{title:'El siguiente paso',description:'Añade una tarea al proyecto.',action:'Crear tarea'},
 thread:{title:'Abre una conversación',description:'Comparte una pregunta o una idea con tu equipo.',action:'Publicar conversación'},
};
export function CreateDialog({mode,onClose,projectId,groupId}:{mode:CreateMode|null;onClose:()=>void;projectId?:string;groupId?:string}) {
 const s=useWorkspace();const inputRef=useRef<HTMLInputElement>(null);
 const [title,setTitle]=useState('');const [body,setBody]=useState('');const [group,setGroup]=useState('personal');const [folder,setFolder]=useState('');const [url,setUrl]=useState('');const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [drag,setDrag]=useState(false);const [assignee,setAssignee]=useState('AH');
 useEffect(()=>{if(mode){setTitle('');setBody('');setGroup(groupId||'personal');setFolder('');setUrl('');setFiles([]);setBusy(false);setAssignee('AH');}},[mode,groupId]);
 const project=s.projects.find(p=>p.id===projectId);
 function chooseFiles(incoming:FileList|File[]|null){if(!incoming)return;const arr=Array.from(incoming);if(arr.some(f=>f.size>20*1024*1024)){toast.error('En esta demo, cada archivo puede pesar hasta 20 MB.');return;}setFiles(prev=>[...prev,...arr]);}
 function submit(e:FormEvent){e.preventDefault();}
 return <Dialog open={!!mode} onOpenChange={o=>{if(!o&&!busy)onClose();}}><DialogContent className="nexo-dialog"><DialogHeader><DialogTitle>{mode?labels[mode].title:''}</DialogTitle><DialogDescription>{mode?labels[mode].description:''}</DialogDescription></DialogHeader>{mode&&<form onSubmit={submit}>
  <p id="save-pending" className="form-note" role="status"><Info size={13}/>El guardado todavía no está disponible. Puedes revisar el formulario; los datos no se guardarán.</p>
  {mode==='file'?<><div className={`drop-zone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);chooseFiles(e.dataTransfer.files);}}><Upload size={30} strokeWidth={1.4}/><strong>Arrastra tus archivos aquí</strong><span>o elígelos desde tu dispositivo</span><Button type="button" variant="outline" onClick={()=>inputRef.current?.click()}>Seleccionar archivos</Button><input ref={inputRef} type="file" multiple hidden onChange={e=>chooseFiles(e.target.files)}/><span>Hasta 20 MB por archivo en esta demo</span></div>{files.map((f,i)=><div className="selected-file" key={`${f.name}-${i}`}><FileText size={15}/><span className="flex-1 truncate">{f.name}</span><button type="button" aria-label={`Quitar ${f.name}`} onClick={()=>setFiles(fs=>fs.filter((_,j)=>i!==j))}><X size={14}/></button></div>)}</>:<div className="form-field"><label htmlFor="create-title">{mode==='group'?'Nombre del grupo':mode==='project'?'Nombre del proyecto':'Título'}</label><Input id="create-title" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100} placeholder={mode==='project'?'Por ejemplo, nuestro próximo concierto':mode==='group'?'Por ejemplo, Banda Norte':'Dale un título claro'} aria-describedby="save-pending" autoFocus/></div>}
  {mode==='project'&&<div className="form-field"><label>Ubicación</label><Choice value={group} onChange={setGroup} label="Ubicación del proyecto" items={[{value:'personal',label:'Mi espacio personal'},...s.groups.map(g=>({value:g.id,label:g.name}))]}/></div>}
  {mode==='link'&&<div className="form-field"><label htmlFor="create-url">Enlace</label><Input id="create-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} required placeholder="https://"/></div>}
  {mode==='task'?<><div className="form-field"><label>Responsable</label><Choice value={assignee} onChange={setAssignee} label="Responsable de la tarea" items={[{value:'none',label:'Sin asignar'},...(project?.members||[me]).map(m=>({value:m.initials,label:m.name}))]}/></div><div className="form-field"><label htmlFor="create-date">Fecha objetivo (opcional)</label><Input id="create-date" value={body} onChange={e=>setBody(e.target.value)} placeholder="Por ejemplo, 23 sep" maxLength={40}/></div></>:mode!=='file'&&<div className="form-field"><label htmlFor="create-body">{mode==='note'?'Contenido':mode==='thread'?'Mensaje':'Descripción (opcional)'}</label><Textarea id="create-body" value={body} onChange={e=>setBody(e.target.value)} rows={mode==='note'?7:3} required={mode==='note'||mode==='thread'} maxLength={15000} placeholder={mode==='note'?'Empieza a escribir…':'Un poco de contexto para el equipo…'}/></div>}
  {['file','note','link'].includes(mode)&&<div className="form-field"><label htmlFor="create-folder">Carpeta (opcional)</label><Input id="create-folder" value={folder} onChange={e=>setFolder(e.target.value)} placeholder="Por ejemplo, Documentación" maxLength={60}/></div>}
  <div className="dialog-actions"><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit" disabled aria-describedby="save-pending">{labels[mode].action}</Button></div>
 </form>}</DialogContent></Dialog>;
}

function newMember(email:string,role:Role):Member {const name=email.trim();return {name,initials:name.slice(0,2).toUpperCase(),role,color:'blue',source:'direct'};}
export function ShareDialog({open,onClose,project}:{open:boolean;onClose:()=>void;project:Project}) {
 const s=useWorkspace();const [email,setEmail]=useState('');const [role,setRole]=useState<Role>('Lector');const [group,setGroup]=useState('');const ownerGroup=s.groups.find(g=>g.id===project.groupId);
 useEffect(()=>{if(open){setEmail('');setRole('Lector');setGroup('');}},[open]);
 function addPerson(e:FormEvent){e.preventDefault();if(!s.canManage||!email.trim())return;if(project.members.some(m=>m.name.toLowerCase()===email.trim().toLowerCase())){toast.error('Esta persona ya tiene acceso.');return;}s.setProjects(ps=>ps.map(p=>p.id===project.id?{...p,members:[...p.members,newMember(email,role)]}:p));s.log(project.id,'añadió un acceso',email.trim());setEmail('');toast.success('Acceso añadido a la demo. No se enviaron invitaciones.');}
 function updatePerson(name:string,next:Role){if(!s.canManage)return;s.setProjects(ps=>ps.map(p=>p.id===project.id?{...p,members:p.members.map(m=>m.name===name?{...m,role:next}:m)}:p));toast.success('Rol actualizado en esta sesión');}
 function shareGroup(){if(!s.canManage||!group)return;s.setProjects(ps=>ps.map(p=>p.id===project.id?{...p,sharedGroupIds:[...p.sharedGroupIds,group]}:p));s.log(project.id,'compartió con el grupo',s.groups.find(g=>g.id===group)?.name||group);setGroup('');toast.success('El proyecto ya aparece en la página del grupo');}
 async function copy(){try{await navigator.clipboard.writeText(`${window.location.origin}/proyectos/${project.id}`);toast.success('Enlace copiado. Los permisos no cambian.');}catch{toast.error('No se pudo copiar el enlace.');}}
 const availableGroups=s.groups.filter(g=>g.id!==project.groupId&&!project.sharedGroupIds.includes(g.id));
 return <Dialog open={open} onOpenChange={o=>{if(!o)onClose();}}><DialogContent className="nexo-dialog"><DialogHeader><DialogTitle>{s.canManage?'Compartir proyecto':'Accesos al proyecto'}</DialogTitle><DialogDescription>{project.name}</DialogDescription></DialogHeader>{s.canManage&&<Tabs defaultValue="people"><TabsList variant="line"><TabsTrigger value="people">Personas</TabsTrigger><TabsTrigger value="groups">Grupos</TabsTrigger></TabsList><TabsContent value="people"><form onSubmit={addPerson} className="invite-row"><Input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="Correo electrónico" aria-label="Correo de la persona"/><Choice label="Rol del nuevo acceso" value={role} onChange={v=>setRole(v as Role)} items={['Lector','Editor','Administrador'].map(v=>({value:v,label:v}))}/><Button type="submit" disabled={!email.trim()}>Añadir</Button></form></TabsContent><TabsContent value="groups"><div className="invite-row"><Choice value={group} onChange={setGroup} label="Grupo con el que compartir" items={availableGroups.map(g=>({value:g.id,label:g.name}))}/><Button onClick={shareGroup} disabled={!group}>Compartir</Button></div><p className="small-caption">El grupo recibe acceso de lectura al mismo proyecto.</p></TabsContent></Tabs>}
 <div>{project.members.map(m=>{const inherited=ownerGroup?.members.some(x=>x.name===m.name)&&m.name!==me.name&&m.source!=='direct';return <div className="member-row" key={m.name}><Avatar initials={m.initials} color={m.color}/><div className="member-copy"><strong>{m.name}{m.name===me.name?' (tú)':''}</strong><small>{m.name===me.name?'Propietario':inherited?`Heredado de ${ownerGroup?.name}`:'Acceso directo'}</small></div>{s.canManage&&m.name!==me.name&&!inherited?<><Choice label={`Rol de ${m.name}`} value={m.role} onChange={v=>updatePerson(m.name,v as Role)} items={['Lector','Editor','Administrador'].map(v=>({value:v,label:v}))}/><Button variant="ghost" size="icon" aria-label={`Retirar acceso de ${m.name}`} onClick={()=>{s.setProjects(ps=>ps.map(p=>p.id===project.id?{...p,members:p.members.filter(x=>x.name!==m.name)}:p));toast.success('Acceso directo retirado en esta sesión');}}><X size={13}/></Button></>:<span className="role-badge">{m.name===me.name?'Propietario':m.role}</span>}</div>;})}{project.sharedGroupIds.map(id=>{const g=s.groups.find(x=>x.id===id);return g?<div className="member-row" key={id}><span className={`group-symbol tone-${g.color}`}>{g.symbol}</span><div className="member-copy"><strong>{g.name}</strong><small>Acceso para sus integrantes</small></div><span className="role-badge">Lector</span>{s.canManage&&<Button variant="ghost" size="icon" aria-label={`Retirar acceso de ${g.name}`} onClick={()=>{s.setProjects(ps=>ps.map(p=>p.id===project.id?{...p,sharedGroupIds:p.sharedGroupIds.filter(x=>x!==id)}:p));toast.success('Acceso del grupo retirado en esta sesión');}}><X size={13}/></Button>}</div>:null;})}</div><div className="share-link-box"><LockKeyhole size={19}/><div className="flex-1"><strong>Solo personas con acceso</strong><p>Copiar el enlace no cambia los permisos.</p></div><Button variant="outline" onClick={copy} size="icon" aria-label="Copiar enlace del proyecto"><Copy size={15}/></Button></div><p className="form-note"><Info size={13}/>Los accesos de esta demo no envían invitaciones.</p></DialogContent></Dialog>;
}

export function GroupMembersDialog({open,onClose,group}:{open:boolean;onClose:()=>void;group:Group}) {const s=useWorkspace();const [email,setEmail]=useState('');function add(e:FormEvent){e.preventDefault();if(!s.canManage||!email.trim())return;if(group.members.some(m=>m.name.toLowerCase()===email.trim().toLowerCase())){toast.error('Esta persona ya pertenece al grupo.');return;}const member=newMember(email,'Editor');s.setGroups(gs=>gs.map(g=>g.id===group.id?{...g,members:[...g.members,member]}:g));s.setProjects(ps=>ps.map(p=>p.groupId===group.id?{...p,members:p.members.some(m=>m.name===member.name)?p.members:[...p.members,{...member,source:group.id}]}:p));setEmail('');toast.success('Integrante añadido a esta demo. No se envió una invitación.');}return <Dialog open={open} onOpenChange={o=>{if(!o)onClose();}}><DialogContent className="nexo-dialog"><DialogHeader><DialogTitle>El equipo de {group.name}</DialogTitle><DialogDescription>Un grupo que te acompaña en más de un proyecto.</DialogDescription></DialogHeader>{s.canManage&&<form className="invite-row" onSubmit={add}><Input type="email" placeholder="Correo del nuevo integrante" aria-label="Correo del nuevo integrante" required value={email} onChange={e=>setEmail(e.target.value)}/><Button type="submit" disabled={!email.trim()}><Plus size={15}/>Añadir</Button></form>}<div>{group.members.map(m=><div className="member-row" key={m.name}><Avatar initials={m.initials} color={m.color}/><div className="member-copy"><strong>{m.name}</strong><small>{m.name===me.name?'Propietario del grupo':'Integrante del grupo'}</small></div><span className="role-badge">{m.name===me.name?'Administrador':'Miembro'}</span></div>)}</div><p className="form-note"><Users size={14}/>Los nuevos integrantes aparecen también en los proyectos del grupo. Los cambios duran esta sesión y no envían invitaciones.</p></DialogContent></Dialog>;}
