'use client';
import { useState, useEffect, useCallback, type CSSProperties } from 'react';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { Search, ChevronRight, ChevronDown, Plus, Folder, FolderOpen, LayoutGrid, List, Users, Layers, Clock3, CheckSquare2, MessageSquare, Share2, MoreHorizontal, LockKeyhole, ArrowUpRight, X, FileText, Upload, Download, Pencil, Copy, ArrowLeft, Info } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarFooter, SidebarInset, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/table';
import { CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from '@/components/ui/command';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { ApiError, logout, getProject, getGroup, listProjectGroups, listGroupProjects, listMembers, downloadFile, updateFile, replaceFile, deleteFile, type ProjectDTO, type GroupDTO, type ArchivoDTO } from '@/lib/api';
import { useRemote } from '@/hooks/use-remote';
import { useWorkspace, WorkspaceProvider } from './store';
import { Avatar, ProjectIcon, Choice, EmptyView } from './ui';
import { CreateDialog, EditSpaceDialog, ShareDialog, GroupMembersDialog, VisibilityChoice, ConfirmAction, type CreateMode } from './dialogs';
import { RemoteState, FormError, asError, initials, colorFor } from './remote-state';

export function Workspace() {return <WorkspaceProvider><AuthenticatedWorkspace/></WorkspaceProvider>;}
function AuthenticatedWorkspace() {
 const s=useWorkspace();const router=useRouter();
 useEffect(()=>{if(!s.authenticated)router.replace('/login');},[s.authenticated,router]);
 return s.authenticated?<WorkspaceContent/>:<p role="status">Volviendo al inicio de sesión…</p>;
}
function WorkspaceContent() {
 const s=useWorkspace();const path=usePathname();const router=useRouter();const parts=path.split('/').filter(Boolean);const isGroupRoute=parts[0]==='grupos';
 const [create,setCreate]=useState<CreateMode|null>(null);const [searchOpen,setSearchOpen]=useState(false);
 const projects=s.projects.data||[];const groups=s.groups.data||[];const identity=s.identity.data;
 const current=parts[1]?(isGroupRoute?groups:projects).find(item=>String(item.id)===parts[1]):undefined;
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();setSearchOpen(open=>!open);}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[]);
 return <SidebarProvider className="nexo-shell" style={{'--sidebar-width':'230px'} as CSSProperties}>
  <Sidebar className="nexo-sidebar"><SidebarHeader className="p-0"><Link href="/proyectos" className="brand"><img src="/favicon.svg" alt="" className="brand-logo"/>nexo<span style={{fontSize:17,color:'#a39da9',marginLeft:-7}}>.</span></Link><div className="workspace-switch"><span className="workspace-avatar"><Layers size={16}/></span><span><strong>Mi espacio</strong><small>Espacio de trabajo</small></span><Layers size={14}/></div></SidebarHeader>
   <SidebarContent><SidebarGroup><SidebarMenu><SidebarMenuItem><SidebarMenuButton asChild isActive={!isGroupRoute}><Link href="/proyectos"><FolderOpen size={18}/><span>Proyectos</span>{s.projects.status==='ready'&&<span className="nav-count">{projects.length}</span>}</Link></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton asChild isActive={isGroupRoute}><Link href="/grupos"><Users size={18}/><span>Grupos</span>{s.groups.status==='ready'&&<span className="nav-count">{groups.length}</span>}</Link></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup>
    <SidebarGroup><SidebarGroupLabel>TUS GRUPOS</SidebarGroupLabel><SidebarMenu>{groups.map(group=><SidebarMenuItem key={group.id}><SidebarMenuButton asChild isActive={isGroupRoute&&parts[1]===String(group.id)}><Link href={`/grupos/${group.id}`}><span className={`group-symbol tone-${colorFor(group.id)}`}>{initials(group.nombre)}</span><span>{group.nombre}</span></Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>
    <SidebarGroup><SidebarGroupLabel>PROYECTOS FIJADOS</SidebarGroupLabel><p className="small-caption">Esta función estará disponible más adelante.</p></SidebarGroup>
   </SidebarContent><SidebarFooter className="sidebar-bottom"><Button variant="outline" onClick={()=>{logout();router.replace('/login');}}>Cerrar sesión</Button><div className="user-profile"><Avatar initials={identity?initials(identity.username):'—'}/><div><strong>{identity?.username||'Mi cuenta'}</strong><small>{identity?`ID ${identity.id}`:'Sesión iniciada'}</small></div></div></SidebarFooter>
  </Sidebar>
  <SidebarInset className="nexo-main"><header className="topbar"><SidebarTrigger className="mobile-trigger" aria-label="Abrir navegación"/><nav className="breadcrumbs" aria-label="Ruta de navegación"><span className="breadcrumb-parent"><FolderOpen size={15}/></span><Link href={isGroupRoute?'/grupos':'/proyectos'} className="breadcrumb-parent">Mi espacio</Link><ChevronRight size={13} className="breadcrumb-parent"/><span>{current?.nombre||(isGroupRoute?'Grupos':'Proyectos')}</span></nav><div className="topbar-tools"><button className="global-search-button" onClick={()=>setSearchOpen(true)} aria-label="Buscar en el espacio"><Search size={16}/><span>Buscar en el espacio</span><kbd>⌘ K</kbd></button><span className="topbar-divider"/><Avatar initials={identity?initials(identity.username):'—'} small/></div></header>
   {s.identity.status==='error'&&<div className="content-panel"><RemoteState state={s.identity} label="tu cuenta"/></div>}
   {parts[1]?(isGroupRoute?<GroupRoute key={parts[1]} id={Number(parts[1])}/>:<ProjectRoute key={parts[1]} id={Number(parts[1])}/>):isGroupRoute?<GroupList onCreate={()=>setCreate('group')}/>:<ProjectList onCreate={()=>setCreate('project')}/>}
  </SidebarInset>
  {create&&<CreateDialog mode={create} onClose={()=>setCreate(null)}/>}
  <CommandDialog open={searchOpen} onOpenChange={setSearchOpen} title="Buscar en el espacio" description="Busca entre los proyectos y archivos cargados para tu cuenta."><CommandInput placeholder="Busca un proyecto o archivo…"/><CommandList>{s.projects.status!=='ready'||s.files.status!=='ready'?<div className="p-4"><RemoteState state={s.projects} label="proyectos"/><RemoteState state={s.files} label="archivos"/></div>:<CommandEmpty>No encontramos coincidencias.</CommandEmpty>}<CommandGroup heading="Proyectos">{projects.map(project=><CommandItem key={project.id} value={`proyecto ${project.id} ${project.nombre}`} onSelect={()=>{setSearchOpen(false);router.push(`/proyectos/${project.id}`);}}><FolderOpen size={16}/>{project.nombre}</CommandItem>)}</CommandGroup><CommandGroup heading="Archivos">{s.files.data?.map(file=><CommandItem key={file.id} value={`archivo ${file.id} ${file.nombre_original}`} onSelect={()=>{setSearchOpen(false);router.push(`/proyectos/${file.proyecto}?recurso=${file.id}`);}}><FileText size={16}/>{file.nombre_original}</CommandItem>)}</CommandGroup></CommandList></CommandDialog>
  <Toaster position="bottom-right" theme="light" richColors closeButton/>
 </SidebarProvider>;
}
function ProjectCard({project}:{project:ProjectDTO}) {
 const s=useWorkspace();return <Link href={`/proyectos/${project.id}`} className="project-card"><div className="project-card-top"><ProjectIcon project={{icon:'layers',color:colorFor(project.id)}}/><span className="status-badge">{project.equipos.length} grupos</span></div><h2>{project.nombre}</h2><p>{project.descripcion||'Sin descripción'}</p><div className="project-card-footer"><span>{s.files.status==='ready'?`${s.files.data?.filter(file=>file.proyecto===project.id).length} archivos visibles`:'Archivos del proyecto'}</span><Users size={16}/></div></Link>;
}
function ProjectList({onCreate}:{onCreate:()=>void}) {
 const s=useWorkspace();const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');
 const projects=(s.projects.data||[]).filter(project=>project.nombre.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==='all'||project.equipos.includes(Number(filter))));
 return <div className="list-page"><div className="page-heading"><div><h1>Proyectos</h1><p>{s.projects.status==='ready'?`${s.projects.data?.length} proyectos accesibles para tu cuenta.`:'Tu espacio para proyectos personales y compartidos.'}</p></div><Button onClick={onCreate} disabled={!s.identity.data?.permissions.create_project}><Plus size={16}/>Nuevo proyecto</Button></div><div className="resource-toolbar"><label className="filter-search"><Search size={15}/><input placeholder="Buscar un proyecto…" aria-label="Buscar proyectos" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="toolbar-actions"><Choice value={filter} onChange={setFilter} label="Filtrar proyectos por grupo" items={[{value:'all',label:'Todos los proyectos'},...(s.groups.data||[]).map(group=>({value:String(group.id),label:group.nombre}))]}/></div></div><RemoteState state={s.projects} label="proyectos"/>{s.projects.status==='ready'&&(projects.length?<div className="project-grid">{projects.map(project=><ProjectCard key={project.id} project={project}/>)}</div>:<EmptyView title={s.projects.data?.length?'No hay coincidencias':'Tu primer proyecto está por empezar'} description={s.projects.data?.length?'Prueba otra búsqueda o cambia el filtro.':'Crea un proyecto para reunir tus archivos y tu equipo.'}/>)}<section className="files-section"><div className="section-label"><h2>Archivos disponibles</h2></div><RemoteState state={s.files} label="archivos"/>{s.files.status==='ready'&&(s.files.data?.length?<FileTable files={s.files.data}/>:<EmptyView title="Todavía no hay archivos" description="Puedes crear proyectos y grupos aunque todavía no tengas archivos."/>)}</section></div>;
}
function GroupList({onCreate}:{onCreate:()=>void}) {
 const s=useWorkspace();return <div className="list-page"><div className="page-heading"><div><h1>Tus grupos</h1><p>{s.groups.status==='ready'?`${s.groups.data?.length} grupos para tus proyectos compartidos.`:'Un lugar para tus proyectos compartidos.'}</p></div><Button onClick={onCreate} disabled={!s.identity.data?.permissions.create_group}><Plus size={16}/>Crear grupo</Button></div><RemoteState state={s.groups} label="grupos"/>{s.groups.status==='ready'&&(s.groups.data?.length?<div className="group-grid">{s.groups.data.map(group=><Link href={`/grupos/${group.id}`} className="group-card" key={group.id}><div className="group-card-top"><span className={`group-symbol tone-${colorFor(group.id)}`}>{initials(group.nombre)}</span><h2>{group.nombre}</h2><p>{group.equipo_recurrente?'Equipo recurrente':'Equipo de trabajo'}</p><Users size={22}/></div><div className="group-card-bottom"><span>{group.usuarios.length} integrantes</span><ArrowUpRight size={16}/></div></Link>)}</div>:<EmptyView title="Tu primer grupo está por empezar" description="Crea un grupo para trabajar con otras personas."/>)}</div>;
}
function validId(id:number){return Number.isSafeInteger(id)&&id>0;}
function ProjectRoute({id}:{id:number}) {
 const s=useWorkspace();const load=useCallback(()=>validId(id)?getProject(id):Promise.reject(new ApiError(404,'No encontramos este proyecto.')),[id]);const project=useRemote(load,true,s.revision);
 return project.data?<ProjectView project={project.data}/>:<div className="list-page"><RemoteState state={project} label="proyecto"/><Button asChild variant="outline" className="mt-5"><Link href="/proyectos"><ArrowLeft/>Volver a proyectos</Link></Button></div>;
}
function GroupRoute({id}:{id:number}) {
 const s=useWorkspace();const load=useCallback(()=>validId(id)?getGroup(id):Promise.reject(new ApiError(404,'No encontramos este grupo.')),[id]);const group=useRemote(load,true,s.revision);
 return group.data?<GroupView group={group.data}/>:<div className="list-page"><RemoteState state={group} label="grupo"/><Button asChild variant="outline" className="mt-5"><Link href="/grupos"><ArrowLeft/>Volver a grupos</Link></Button></div>;
}
function ProjectView({project}:{project:ProjectDTO}) {
 const s=useWorkspace();const router=useRouter();const params=useSearchParams();const [tab,setTab]=useState('recursos');const [create,setCreate]=useState(false);const [share,setShare]=useState(false);const [edit,setEdit]=useState(false);
 const load=useCallback(()=>listProjectGroups(project.id),[project.id]);const groups=useRemote(load,true,s.revision);const files=(s.files.data||[]).filter(file=>file.proyecto===project.id);const resourceId=params.get('recurso');const selected=files.find(file=>String(file.id)===resourceId);
 function closeResource(){router.replace(`/proyectos/${project.id}`,{scroll:false});}
 return <><div className="project-head"><ProjectIcon project={{icon:'layers',color:colorFor(project.id)}} large/><div className="project-head-text"><h1>{project.nombre}</h1><p>{project.descripcion||'Sin descripción'}</p></div><div className="project-head-actions"><Button variant="outline" onClick={()=>setShare(true)}><Share2 size={15}/>{project.permissions.manage_teams?'Compartir':'Ver accesos'}</Button>{project.permissions.upload_files&&<DropdownMenu><DropdownMenuTrigger asChild><Button><Plus size={16}/>Añadir<ChevronDown size={13}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>setCreate(true)}><Upload/>Subir archivos</DropdownMenuItem><DropdownMenuItem disabled>Notas y enlaces · Próximamente</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Opciones del proyecto"><MoreHorizontal size={18}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={!project.permissions.edit&&!project.permissions.delete} onClick={()=>setEdit(true)}><Pencil/>Editar proyecto</DropdownMenuItem><DropdownMenuItem onClick={()=>void copyLink(`/proyectos/${project.id}`)}><Copy/>Copiar enlace</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>
  <Tabs value={tab} onValueChange={setTab} className="project-tabs"><div className="project-tabbar"><TabsList variant="line"><TabsTrigger value="recursos"><FolderOpen/>Recursos{s.files.status==='ready'&&<span className="tab-count">{files.length}</span>}</TabsTrigger><TabsTrigger value="tareas"><CheckSquare2/>Tareas</TabsTrigger><TabsTrigger value="conversaciones"><MessageSquare/>Conversaciones</TabsTrigger><TabsTrigger value="actividad"><Clock3/>Actividad</TabsTrigger></TabsList><span className="role-badge"><LockKeyhole size={12}/>Acceso por equipo</span></div>
   <TabsContent value="recursos" className="no-margin"><div className="project-body"><Resources files={files} project={project}/><aside className="project-aside"><div className="aside-title">En este proyecto<button onClick={()=>setShare(true)} aria-label="Ver accesos"><MoreHorizontal size={17}/></button></div><div className="aside-access"><LockKeyhole size={12}/>Acceso por equipos</div><div className="aside-divider"/><div className="aside-title">Grupos asociados</div><RemoteState state={groups} label="grupos"/>{groups.data?.map(group=><div className="about-row" key={group.id}>{group.permissions.manage_members?<Link href={`/grupos/${group.id}`}>{group.nombre}</Link>:<strong>{group.nombre}</strong>}</div>)}<div className="aside-divider"/><div className="aside-title">Tus permisos</div><p className="small-caption">{project.permissions.upload_files?'Puedes añadir archivos.':'No puedes añadir archivos.'} {project.permissions.manage_teams?'Puedes gestionar los equipos asociados.':''}</p><div className="aside-note"><Layers size={17}/><p>Un mismo recurso, siempre actualizado para todo el equipo.</p></div></aside></div></TabsContent>
   {['tareas','conversaciones','actividad'].map(value=><TabsContent key={value} value={value}><div className="content-panel"><EmptyView title="Próximamente" description="Esta función todavía no está disponible. Los archivos y accesos del proyecto sí se guardan en tu cuenta."/></div></TabsContent>)}
  </Tabs>
  {create&&<CreateDialog mode="file" project={project} onClose={()=>setCreate(false)}/>}{share&&<ShareDialog project={project} onClose={()=>setShare(false)}/>}
  {edit&&<EditSpaceDialog space={{kind:'project',data:project}} onClose={()=>setEdit(false)}/>}
  {selected&&<FileDetail key={selected.id} file={selected} onClose={closeResource}/>}{resourceId&&!selected&&s.files.status==='ready'&&<Sheet open onOpenChange={open=>{if(!open)closeResource();}}><SheetContent className="file-details"><SheetHeader><SheetTitle>Archivo no disponible</SheetTitle><SheetDescription>El archivo no existe en este proyecto o ya no tienes acceso.</SheetDescription></SheetHeader></SheetContent></Sheet>}
 </>;
}
function GroupView({group}:{group:GroupDTO}) {
 const s=useWorkspace();const [membersOpen,setMembersOpen]=useState(false);const [create,setCreate]=useState(false);const [edit,setEdit]=useState(false);const load=useCallback(()=>listGroupProjects(group.id),[group.id]);const projects=useRemote(load,true,s.revision);const loadMembers=useCallback(()=>listMembers(group.id),[group.id]);const members=useRemote(loadMembers,true,s.revision);
 return <div className="list-page">
  <div className="group-hero"><span className={`group-symbol tone-${colorFor(group.id)}`}>{initials(group.nombre)}</span><div className="group-hero-copy"><h1>{group.nombre}</h1><p>{group.equipo_recurrente?'Equipo recurrente':'Equipo de trabajo'}</p><button onClick={()=>setMembersOpen(true)} aria-label="Ver integrantes del grupo"><span className="avatar-stack">{members.data?.slice(0,4).map(member=><Avatar key={member.usuario} initials={initials(member.username)} color={colorFor(member.usuario)} small/>)}</span></button></div><Button variant="outline" onClick={()=>setMembersOpen(true)}><Users size={15}/>{group.usuarios.length} integrantes</Button>{(group.permissions.edit||group.permissions.delete)&&<Button variant="ghost" size="icon" aria-label="Editar grupo" onClick={()=>setEdit(true)}><MoreHorizontal size={18}/></Button>}</div>
  <div className="content-panel-heading"><h2>Proyectos del grupo{projects.status==='ready'&&<span className="tab-count">{projects.data?.length}</span>}</h2><Button onClick={()=>setCreate(true)} disabled={!s.identity.data?.permissions.create_project}><Plus size={16}/>Nuevo proyecto</Button></div>
  <RemoteState state={projects} label="proyectos del grupo"/>
  {projects.status==='ready'&&(projects.data?.length?<div className="project-grid">{projects.data.map(project=><ProjectCard key={project.id} project={project}/>)}</div>:<EmptyView title="El primer proyecto está por empezar" description="Crea un proyecto y todo el grupo podrá encontrarlo aquí."/>)}
  {membersOpen&&<GroupMembersDialog group={group} onClose={()=>setMembersOpen(false)}/>}
  {create&&<CreateDialog mode="project" groupId={group.id} onClose={()=>setCreate(false)}/>}
  {edit&&<EditSpaceDialog space={{kind:'group',data:group}} onClose={()=>setEdit(false)}/>}
 </div>;
}
function Resources({files,project}:{files:ArchivoDTO[];project:ProjectDTO}) {
 const s=useWorkspace();const router=useRouter();const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [view,setView]=useState('grid');
 const categories=[...new Set(files.map(file=>file.categoria).filter((value):value is string=>!!value))];const visible=files.filter(file=>(!category||file.categoria===category)&&file.nombre_original.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <section className="resources-main"><div className="resource-toolbar"><label className="filter-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar en los recursos…" aria-label="Buscar recursos"/></label><div className="toolbar-actions"><div className="view-toggle" aria-label="Vista de recursos"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="Vista de cuadrícula" aria-pressed={view==='grid'}><LayoutGrid size={14}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="Vista de lista" aria-pressed={view==='list'}><List size={15}/></button></div></div></div><RemoteState state={s.files} label="archivos"/>
  {s.files.status==='ready'&&<>{categories.length>0&&<><div className="section-label"><h2>Categorías</h2><span>{categories.length} categorías</span></div><div className="folders">{categories.map(value=><button className={`folder-card ${category===value?'selected':''}`} key={value} onClick={()=>setCategory(category===value?'':value)} aria-pressed={category===value}><Folder className="folder-icon" size={27} strokeWidth={1.2}/><span><strong>{value}</strong><small>{files.filter(file=>file.categoria===value).length} archivos</small></span></button>)}</div></>}<div className="files-section"><div className="section-label"><h2>{category||'Todos los recursos'} <span>{visible.length}</span></h2>{category?<button className="clear-filter" onClick={()=>setCategory('')}><X size={12}/>Quitar filtro</button>:<span>Fecha de subida</span>}</div>{visible.length===0?<EmptyView title={files.length?'No hay coincidencias':'Todo listo para tus primeras ideas'} description={files.length?'Prueba otro nombre o cambia los filtros.':'Añade archivos desde el botón Añadir.'}/>:view==='grid'?<div className="resource-grid">{visible.map(file=><button className="resource-card" key={file.id} onClick={()=>router.push(`/proyectos/${project.id}?recurso=${file.id}`,{scroll:false})} aria-label={`Abrir ${file.nombre_original}`}><div className="resource-card-preview"><div className="generic-preview"><FileText size={44}/><span>{file.categoria||'Archivo'}</span></div></div><div className="resource-card-info"><div className="resource-card-title"><FileText size={17}/><strong>{file.nombre_original}</strong></div><div className="resource-card-meta"><span>{file.usuario===s.identity.data?.id?s.identity.data.username:`Usuario #${file.usuario}`}</span><span>{new Date(file.fecha_subido).toLocaleDateString('es-CL')}</span></div></div></button>)}</div>:<FileTable files={visible}/>}</div></>}
  <div className="resource-footnote"><LockKeyhole size={11}/>Archivos visibles para tu cuenta en {project.nombre}</div>
 </section>;
}
function FileTable({files}:{files:ArchivoDTO[]}) {
 return <Table className="resource-table"><TableHeader><TableRow><TableHead>Nombre</TableHead><TableHead className="optional-column">Categoría</TableHead><TableHead>Subido</TableHead></TableRow></TableHeader><TableBody>{files.map(file=><TableRow key={file.id}><TableCell className="table-name-cell"><span className="resource-table-name"><FileText size={16}/><Link href={`/proyectos/${file.proyecto}?recurso=${file.id}`}>{file.nombre_original}</Link></span></TableCell><TableCell className="optional-column">{file.categoria||'Sin categoría'}</TableCell><TableCell>{new Date(file.fecha_subido).toLocaleDateString('es-CL')}</TableCell></TableRow>)}</TableBody></Table>;
}
async function copyLink(path:string){try{await navigator.clipboard.writeText(window.location.origin+path);toast.success('Enlace copiado. Los permisos no cambian.');}catch{toast.error('No se pudo copiar el enlace.');}}
function FileDetail({file,onClose}:{file:ArchivoDTO;onClose:()=>void}) {
 const s=useWorkspace();const [editing,setEditing]=useState(false);const [name,setName]=useState(file.nombre_original);const [category,setCategory]=useState(file.categoria||'');const [projectWide,setProjectWide]=useState(file.global);const [busy,setBusy]=useState(false);const [error,setError]=useState<Error|null>(null);
 const [preview,setPreview]=useState<{url:string;type:string}|null>(null);const [previewLoading,setPreviewLoading]=useState(false);const [previewError,setPreviewError]=useState<Error|null>(null);
 const [replacement,setReplacement]=useState<File|null>(null);
 useEffect(()=>{
  if(!file.permissions.download||! /\.(png|jpe?g|gif|webp|pdf)$/i.test(file.nombre_original))return;
  let active=true;let url:string|undefined;setPreview(null);setPreviewError(null);setPreviewLoading(true);
  downloadFile(file.id).then(blob=>{if(!active)return;const type=blob.type.split(';')[0];if(['image/png','image/jpeg','image/gif','image/webp','application/pdf'].includes(type)){url=URL.createObjectURL(blob);setPreview({url,type});}}).catch(cause=>{if(active)setPreviewError(asError(cause));}).finally(()=>{if(active)setPreviewLoading(false);});
  return()=>{active=false;if(url)URL.revokeObjectURL(url);};
 },[file.id,file.permissions.download]);
 async function save(){if(busy||!file.permissions.edit)return;setBusy(true);setError(null);try{const metadata={nombre_original:name.trim(),categoria:category.trim(),global:projectWide};if(replacement)await replaceFile(file.id,replacement,metadata);else await updateFile(file.id,metadata);s.files.retry();onClose();toast.success('Archivo actualizado');}catch(cause){setError(asError(cause));}finally{setBusy(false);}}
 async function remove(){if(busy||!file.permissions.delete)return;setBusy(true);setError(null);try{await deleteFile(file.id);s.files.retry();onClose();toast.success('Archivo eliminado');}catch(cause){setError(asError(cause));}finally{setBusy(false);}}
 async function download(){if(busy||!file.permissions.download)return;setBusy(true);setError(null);try{const blob=await downloadFile(file.id);const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=file.nombre_original;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(cause){setError(asError(cause));}finally{setBusy(false);}}
 return <Sheet open onOpenChange={open=>{if(!open&&!busy){if(editing){toast('Guarda o descarta los cambios antes de cerrar.');return;}onClose();}}}><SheetContent className="file-details"><SheetHeader><SheetTitle>{file.nombre_original}</SheetTitle><SheetDescription>{file.categoria||'Sin categoría'} · Subido por {file.usuario===s.identity.data?.id?s.identity.data.username:`Usuario #${file.usuario}`}</SheetDescription></SheetHeader><div className="file-detail-toolbar"><span className="status-badge"><LockKeyhole size={12}/>{file.global?'Todos los equipos del proyecto':'Equipos compartidos con el autor'}</span><div className="file-detail-actions"><Button variant="ghost" size="icon" aria-label="Copiar enlace del recurso" onClick={()=>void copyLink(`/proyectos/${file.proyecto}?recurso=${file.id}`)}><Copy size={14}/></Button>{file.permissions.edit&&!editing&&<Button variant="outline" onClick={()=>setEditing(true)} disabled={busy}><Pencil size={13}/>Editar datos</Button>}{file.permissions.download&&<Button variant="outline" onClick={()=>void download()} disabled={busy}><Download size={14}/>Descargar</Button>}</div></div><FormError error={error}/>
  {editing?<form className="file-detail-content" onSubmit={event=>{event.preventDefault();void save();}}><div className="form-field"><label htmlFor="file-name">Nombre</label><Input id="file-name" value={name} onChange={event=>setName(event.target.value)} maxLength={255} required disabled={busy}/></div><div className="form-field"><label htmlFor="file-category">Categoría</label><Input id="file-category" value={category} onChange={event=>setCategory(event.target.value)} maxLength={100} disabled={busy}/></div><div className="form-field"><label htmlFor="file-replacement">Reemplazar archivo (opcional)</label><Input id="file-replacement" type="file" disabled={busy} onChange={event=>setReplacement(event.target.files?.[0]||null)}/><p className="small-caption">Reemplaza el contenido actual; no se conserva un historial de versiones.</p></div><VisibilityChoice value={projectWide} onChange={setProjectWide} disabled={busy}/><div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>{setEditing(false);setName(file.nombre_original);setCategory(file.categoria||'');setProjectWide(file.global);setReplacement(null);setError(null);}}>Descartar</Button><Button type="submit" disabled={busy||!name.trim()}>{busy?'Guardando…':'Guardar cambios'}</Button></div></form>:<div className="file-detail-content">{previewLoading?<p role="status">Cargando vista previa…</p>:previewError?<FormError error={previewError}/>:preview?preview.type==='application/pdf'?<iframe title={file.nombre_original} src={preview.url} className="pdf-frame" sandbox=""/>:<div className="uploaded-image"><img src={preview.url} alt={file.nombre_original}/></div>:<div className="generic-preview"><FileText size={44}/><span>Vista previa no disponible. Puedes descargar el archivo original.</span></div>}</div>}
  <div className="file-detail-toolbar"><p className="small-caption">Subido el {new Date(file.fecha_subido).toLocaleDateString('es-CL')}</p>{file.permissions.delete&&<ConfirmAction label="Eliminar archivo" description="Se eliminará este archivo del proyecto. Esta acción no se puede deshacer desde la aplicación." disabled={busy} onConfirm={()=>void remove()}/>}</div><p className="form-note"><Info size={13}/>Los comentarios y el historial de versiones todavía no están disponibles.</p>
 </SheetContent></Sheet>;
}
